import { WORKSPACE_TOOL_CATEGORIES } from "@/lib/vanode/constants";
import type { NativeToolKey, VanodePersisted } from "@/lib/vanode/types";

const NATIVE_TOOL_LABELS: Record<NativeToolKey, string> = {
  aiTask: "AI Task Assistant",
  eod: "EOD Reporter",
  chaosCalc: "Chaos Calculator",
  smartNotes: "Smart Notes / Scratch Pad",
  billableHours: "Billable Hours Timetracker",
};

function toolNameById(id: string): string {
  for (const cat of WORKSPACE_TOOL_CATEGORIES) {
    const hit = cat.tools.find((t) => t.id === id);
    if (hit) return hit.name;
  }
  return id;
}

function yesNo(v: boolean): string {
  return v ? "Yes" : "No";
}

function formatList(items: string[], empty = "None"): string {
  return items.length ? items.map((x) => `- ${x}`).join("\n") : `- ${empty}`;
}

/** Builds a human-readable markdown report from VANode persisted state. */
export function formatVanodeHumanReadableReport(data: VanodePersisted): string {
  const exportedAt = new Date().toLocaleString();
  const connectedTools = data.syncedToolIds.map(toolNameById);
  const activeNative = (
    Object.entries(data.nativeTools) as [NativeToolKey, boolean][]
  )
    .filter(([, on]) => on)
    .map(([key]) => NATIVE_TOOL_LABELS[key]);

  const clientLines =
    data.clients.length === 0
      ? ["- No clients added yet."]
      : data.clients.map(
          (c) =>
            `- **${c.name}** (${c.industry || "—"}) · TZ: ${c.timezone}`,
        );

  return [
    "# VANode Workspace Report",
    "",
    `_Exported ${exportedAt}_`,
    "",
    "## VANode Executive Summary",
    "",
    `**Discovery status:** ${data.discoveryComplete ? "Complete" : "Not completed"}`,
    "",
    "**Connected tools**",
    formatList(connectedTools, "No workspace tools selected"),
    "",
    "**Active native tools**",
    formatList(activeNative, "None enabled"),
    "",
    `**Clients:** ${data.clients.length}`,
    ...clientLines,
    "",
    `**Active client lock:** ${
      data.activeClientId
        ? data.clients.find((c) => c.id === data.activeClientId)?.name ??
          data.activeClientId
        : "None (global view)"
    }`,
    "",
    "## Settings",
    "",
    `| Preference | Value |`,
    `| --- | --- |`,
    `| Default client timezone | ${data.settings.defaultClientTimezone} |`,
    `| Email notifications | ${yesNo(data.settings.vaEmailNotifications)} |`,
    `| Slack notifications | ${yesNo(data.settings.vaSlackNotifications)} |`,
    `| Cloud sync for recordings | ${yesNo(data.settings.cloudSyncRecording)} |`,
    "",
    "## Value Metrics",
    "",
    `| Metric | Count |`,
    `| --- | --- |`,
    `| Inbox items triaged | ${data.valueMetrics.inboxTriaged} |`,
    `| Inbox replies sent | ${data.valueMetrics.inboxReplied} |`,
    `| Hours saved this month | ${data.valueMetrics.hoursSavedThisMonth} |`,
    "",
    "## Workspace inventory",
    "",
    `| Area | Count |`,
    `| --- | --- |`,
    `| Vault notes | ${data.notes.length} |`,
    `| EOD logs | ${data.eodLogs.length} |`,
    `| Waiting / blocker tasks | ${data.waitingTasks.length} |`,
    `| Invoices | ${data.invoices.length} |`,
    `| Live transcript sessions | ${data.liveTranscripts.length} |`,
    `| Scratch pad saves | ${data.scratchPadSaves.length} |`,
    "",
    "---",
    "",
    "_Generated by LifeNodeOS VANode. For a full machine restore, use the System Backup (.json) export._",
    "",
  ].join("\n");
}

function triggerDownload(blob: Blob, filename: string) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export function downloadVanodeJsonBackup(data: VanodePersisted) {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
  triggerDownload(blob, `vanode-backup-${Date.now()}.json`);
}

export function downloadVanodeHumanReadableReport(data: VanodePersisted) {
  const md = formatVanodeHumanReadableReport(data);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  triggerDownload(blob, `vanode-report-${Date.now()}.md`);
}
