/**
 * @deprecated Use `kitchenMintCream.ts` — HomeNode and Kitchen share Crisp Mint & Cream.
 */
export {
  KITCHEN_BG_CLASS as ECOSYSTEM_BG_CLASS,
  KITCHEN_BTN_PRIMARY as ECOSYSTEM_BTN_PRIMARY,
  KITCHEN_CHIP_ACTIVE as ECOSYSTEM_CHIP_ACTIVE,
  KITCHEN_CHIP_IDLE as ECOSYSTEM_CHIP_IDLE,
  KITCHEN_INNER_PANEL as ECOSYSTEM_INNER_PANEL,
  KITCHEN_INNER_PANEL_SM as ECOSYSTEM_INNER_PANEL_SM,
  KITCHEN_INPUT_CLASS as ECOSYSTEM_INPUT_CLASS,
  KITCHEN_TEXT as ECOSYSTEM_TEXT,
  KITCHEN_TOGGLE_ACTIVE as ECOSYSTEM_TOGGLE_ACTIVE,
  KITCHEN_TOGGLE_IDLE as ECOSYSTEM_TOGGLE_IDLE,
  KITCHEN_GLASS_PANEL as ECOSYSTEM_GLASS_PANEL,
} from "./kitchenMintCream";
